version: '3'
services:
    lilo-db:
      image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
      environment:
        - 'ACCEPT_EULA=Y'
        - 'SA_PASSWORD=${LILO_DB_PSW}'
        - 'MSSQL_PID=Express'
      container_name: lilo-db
      ports:
        - "1433:1433"
      networks:
        lilo-db-network:
          ipv4_address: 10.5.0.5
    lilo-web-api:
      build:
        dockerfile: ./API/Dockerfile
        context: ../src/
      image: brunocremaferreira/lilodash:dev
      container_name: lilo-web-api
      environment:
        - 'ASPNETCORE_ENVIRONMENT=Development'
        - 'DB_CONNECTION_STRING=${LILO_DB_CONNECTION}'
      ports:
        - "5020:80"
        - "5023:443"
      networks:
        - lilo-db-network
      depends_on:
        - "lilo-db"
networks:
    lilo-db-network:
      driver: bridge
      ipam:
        config:
          - subnet: 10.05.0.0/16
            gateway: 10.5.0.1
