apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilo-db-deployment
spec:
  selector:
    matchLabels:
      app: lilo-db
  template:
    metadata:
      labels:
        app: lilo-db
    spec:
      containers:
      - name: lilo-db-container
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: SA_PASSWORD
          valueFrom:
           secretKeyRef:
            key: SA_PASSWORD
            name: lilo-db-secret
        - name: MSSQL_PID
          value: 'Express'
        volumeMounts:
          - name: lilo-db-pod-volume
            mountPath: "/var/opt/mssql"
      volumes:
        - name: lilo-db-pod-volume
          persistentVolumeClaim:
            claimName: lilo-db-pvc