apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: lilo-stack
spec: 
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: management
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: prometheus
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
