apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilo-web-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lilo-web-api
  template:
    metadata:
      labels:
        app: lilo-web-api
    spec:
      containers:
      - name: lilo-web-api-container
        image: brunocremaferreira/lilodash:latest
        resources:
          requests:
            cpu: "0.2"
            memory: "512Mi"
          limits:
            cpu: "0.9"
            memory: "800Mi"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
           name: lilo-web-app-config-map
      initContainers:
      - name: lilo-db-migrate
        image: brunocremaferreira/lilodash-migration:1.0
        envFrom:
        - configMapRef:
           name: lilo-web-app-config-map