apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilo-web-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lilo-web-api
  template:
    metadata:
      labels:
        app: lilo-web-api
    spec:
      containers:
      - name: lilo-web-api-container
        image: brunocremaferreira/lilodash:latest
        resources:
          requests:
            cpu: "0.2"
            memory: "64Mi"
          limits:
            cpu: "0.9"
            memory: "128Mi"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Production'
        - name: DB_CONNECTION_STRING
          value: ''

