apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilo-web-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lilo-web-api
  template:
    metadata:
      labels:
        app: lilo-web-api
    spec:
      containers:
      - name: lilo-web-api-container
        image: brunocremaferreira/lilodash:latest
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "0.99"
            memory: "1024Mi"
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
           name: lilo-web-app-config-map
      initContainers:
      - name: lilo-db-migrate
        image: brunocremaferreira/lilodash-migration:1.0
        command: ['dotnet-ef', 'database', 'update']
        envFrom:
        - configMapRef:
           name: lilo-web-app-config-map