apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lilo-web-api-hpa
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: lilo-web-api-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50