apiVersion: v1
kind: Service
metadata:
  name: lilo-web-api-service
  namespace: lilo-stack
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
  selector:
    app: lilo-web-api
