apiVersion: v1
kind: Service
metadata:
  name: lilo-web-api-load-balancer-service
  namespace: lilo-stack
spec: 
  selector:
    app: lilo-web-api
  ports:
   - port: 9000
     targetPort: 80
     protocol: TCP
  type: LoadBalancer
  externalIPs:
    - 192.168.0.114
